### ISSUE TITLE
Only one point is visible

### ISSUE THREAD

**Issue by Llaves** [mach0/qchainage#20] opened 2019-09-28 17:01 UTC
I am trying to use QChainage on the file below. I leave all settings at default except Advanced->Divide Feature into x parts, which I set to 25.
When I run this, the result is a single visible point. When I check the attribute table, there are 25 points, All have FID 0, and only one point (point 4 as it happens) has geometry. The rest have no geometry, as witnessed by selecting right-click->zoom to on the feature. 
QGIS 3.4.2 on Windows 7 Pro 64 bit.

[ContDiv.zip](https://github.com/mach0/qchainage/files/3665763/ContDiv.zip)

**Comment by mach0** [comment] 2019-09-30 06:53
Hi and thanks for your report,
Just tested with a "normal" linestring and everything worked perfectly.
Currently investigating why it does not work on your data. (btw: thanks for the test data).
Could take some time as I am busy with work.
If you find something just drop me a note here.

**Comment by HerrRuin** [comment] 2019-12-12 10:09
Hi Llaves, something is wrong with your geometry of the line.
I made a copy of the line inside the shapefile (new fid 3) and with that line it worked as expected.
Try yourself.

[ContDiv_new.zip](https://github.com/mach0/qchainage/files/3955129/ContDiv_new.zip)

**Comment by mach0** [comment] 2019-12-12 10:15
As @HerrRuin already said - there were a problem inside you geometry.
After Converting your testdata using "Multipart to singleparts" than selecting every feature and using "Edit -> Merge selected Features" I was able to divide the geometry into 25 Parts as expected.

Closing this for now as it seems to be a data problem and not a bug in the plugin

**Closed by mach0** 2019-12-12 10:15 UTC
